# Google Cloud Build configuration
# Este archivo define c칩mo construir y desplegar la aplicaci칩n en Google Cloud Run

steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gestus-app:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gestus-app:latest'
      - '.'
    id: 'build-image'

  # Paso 2: Subir la imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gestus-app:$SHORT_SHA'
    id: 'push-image-versioned'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gestus-app:latest'
    id: 'push-image-latest'

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gestus-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gestus-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PORT=8080'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
      - '--set-secrets'
      - 'DB_PASSWORD=db-password:latest,JWT_SECRET=jwt-secret:latest,FIREBASE_SERVICE_ACCOUNT_JSON=firebase-service-account:latest'
      - '--set-env-vars'
      - 'DB_HOST=/cloudsql/${_CLOUDSQL_INSTANCE},DB_PORT=3306,DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}'
    id: 'deploy-cloud-run'

# Im치genes que se crear치n
images:
  - 'gcr.io/$PROJECT_ID/gestus-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/gestus-app:latest'

# Opciones de build
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Sustituciones (variables que debes configurar en Cloud Build)
substitutions:
  _CLOUDSQL_INSTANCE: 'PROJECT_ID:REGION:INSTANCE_NAME'  # Ejemplo: my-project:us-central1:gestus-db
  _DB_NAME: 'webprojectdb'
  _DB_USER: 'gestus'
  _FIREBASE_DATABASE_URL: 'https://gestusproject-default-rtdb.firebaseio.com'

# Timeout del build (en segundos)
timeout: '1200s'

